variable "name" {}
variable "env" {}
variable "subnet_ids" {}
variable "tags" {}
variable "vpc_id" {}
variable "port_no" {}
variable "allow_db_cidr" {}
variable "kms_arn" {}
variable "instance_type" {}
variable "bastion_cidr" {}